version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bloodkey/lab4-ex:compose-app
    container_name: l4_app
    ports:
      - 8000:8000
  
  test:
    build:
      context: .
      dockerfile: Dockerfile2
    image: bloodkey/lab4-ex:compose-test
    container_name: l4_test
    depends_on:
      - app
    network_mode: "host"
